{% set name = "mudirac" %}
{% set version = "1.3.0" %}


package:
  name: mudirac
  version: {{ version }}

source:
  url: https://github.com/muon-spectroscopy-computational-project/mudirac/archive/refs/tags/{{ version }}.tar.gz
  sha256: e50e346c3b9dedb29c11685d42fa9042ee92fd89240aaf07c8fd2342187bece0

build:
  number: 0
  skip: true  # [win]
  skip: true  # [osx]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake
    - make

test:
  commands: mudirac --help

about:
  home: https://muon-spectroscopy-computational-project.github.io/mudirac/
  summary: 'Simulation software that integrates the Dirac equation for muonic atoms to compute their X-Ray transition energies.'
  description: |
    MuDirac is a simulation software that integrates the Dirac equation for muonic atoms to compute their X-Ray transition energies;
    it is written in C++. 
    
    Version 1.3.0 introduces 2-parameter Fermi (2pF) nuclear charge distribution optimisation.
    
    The use and functioning of MuDirac is documented in the paper [S. Sturniolo, A. Hillier, 
    “Mudirac: A Dirac equation solver for elemental analysis with muonic X-rays”, X-Ray Spectrom. 2020;1–17](https://onlinelibrary.wiley.com/doi/full/10.1002/xrs.3212),
    and the 2pF optimisation in the paper [L. Liborio, M. Kumar, S. Devadasan, P. Jones, M. Plummer, A. Hillier, A. Bartok,"MuDirac 1.3.0: A Sustainable Software Tool 
    for Calculating Ground State Nuclear Properties Using Muonic X-Ray Measurements", arXiv:2605.00554 (2026)](https://arxiv.org/abs/2605.00554). 
    Both papers should be cited by any work using this software.

  license: MIT
  license_file: LICENSE
  doc_url: https://muon-spectroscopy-computational-project.github.io/mudirac/
  dev_url: https://github.com/muon-spectroscopy-computational-project/mudirac

extra:
  recipe-maintainers:
    - subindev-d
    - patrick-austin
